# Week Two
## Day 1 (Sunday)
### Module 5 Exercises

#### Module 5 (Set Exercise - Level 1, 2, and 3)

##### Exercises: Level 1

In [362]:
#1Declare an empty list

empty_list1 = []
print(empty_list1) # [] This is an Empty List


#2Declare a list with more than 5 items
Rocks = ['Granite', 'Gneises', 'Marble', 'Limestone', 'Basalt', 'Andesite', 'Pumice']
print(Rocks)

#3Find the length of your list

Rocks_len = len(Rocks)
print(Rocks_len)


#4Get the first item, the middle item and the last item of the list

Rocks_List4 = first_item, second_items, third_items, middle_item, *rest = Rocks
print(first_item)
print(middle_item)
print(last_item)
first_item1 = Rocks[0]
middle_item1 = Rocks[len(Rocks) // 2]
last_item1 = Rocks[-1]
print(first_item1)
print(middle_item1)
print(last_item1)

#5Declare a list called mixed_data_types, put your(name, age, height, marital status, address)

mixed_data_type = ['Name:''Umar','Age:',25, 'Height:', 1.69, 'Marital Statu:', 'Single', 'Adreess:', 'Bauchi']
print(mixed_data_type)

#6Declare a list variable named it_companies and assign initial values Facebook, Google, Microsoft, Apple, IBM, Oracle and Amazon.
it_Companies = 'Facebook', 'Google', 'Microsoft', 'Apple', 'IBM', 'Oracle' and 'Amazon'
list_companies = list(it_Companies)
print(list_companies)

#7Print the list using print()
print(list_companies)

#8Print the number of companies in the list

len_It_Companies = len(list_companies)
print(len_It_Companies)

#9Print the first, middle and last company

list_companies

First_Company = list_companies[0]
middle_Company = list_companies[len(list_companies) // 2]
Last_Company = list_companies[-1]

print(First_Company)
print(middle_Company)
print(Last_Company)

print(First_Company, middle_Company, Last_Company)

#10Print the list after modifying one of the companies
modify_IT_Com = list_companies.append('Geo Data Solution')
print(list_companies)

#11Insert an IT company in the middle of the companies list

list_companies.insert(len(list_companies) // 2, 'Tesla')
print(list_companies)


#12Change one of the it_companies names to uppercase (IBM excluded!)

list_companies[3] = list_companies[3].upper()
print(list_companies)

#13Join the it_companies with a string '#;  '

list_companies
Join_it_Companies = ' #'.join(list_companies)
print(Join_it_Companies)

#14Check if a certain company exists in the it_companies list

Check_Companies = 'Tesla' in list_companies

print(Check_Companies)
if  'Tesla' in list_companies:
    print(f'Yes, Tesla exists in the List!')
else:print(f"No, Tesla doesn't exists in the List!")

#15Sort the list using sort() method
Sort_list_Company = list_companies.sort()

print(list_companies)

#16Reverse the list in descending order using reverse() method
revers_list_company = list_companies.reverse()
print(list_companies)

#17Slice out the first 3 companies from the list
sliceOut_First_three = (list_companies[:3])

print(sliceOut_First_three)

#18Slice out the last 3 companies from the list
sliceOut_Last_three = (list_companies[-3:])

print(sliceOut_Last_three)

#19Slice out the middle IT company or companies from the list

middle_IT_COMPANY = len(list_companies) // 2
print(list_companies[middle_IT_COMPANY])

#20Remove the first IT company from the list

del list_companies[0]
print(list_companies)

#21Remove the middle IT company or companies from the list
del list_companies[3]
print(list_companies)

#22Remove the last IT company from the list
del list_companies[-1]
print(list_companies)

#23Remove all IT companies from the list
del list_companies[:]
print(list_companies)

#24Destroy the IT companies list

claerAll = list_companies.clear()
print(claerAll)

#26Join the following lists:

front_end = ['HTML', 'CSS', 'JS', 'React', 'Redux']
back_end = ['Node','Express', 'MongoDB']

Fullstack = front_end + back_end
print(Fullstack)


#27 After joining the lists in question 26. Copy the joined list and assign it to a variable full_stack, then insert Python and SQL after Redux.
New = ['Python', 'SQL']
Copy_Fullstack = Fullstack.copy()
print(Copy_Fullstack)

Copy_Fullstack.insert(Copy_Fullstack.index('Redux') + 1, 'Python')
Copy_Fullstack.insert(Copy_Fullstack.index("Python") + 1, "SQL")
print(Copy_Fullstack)

[]
['Granite', 'Gneises', 'Marble', 'Limestone', 'Basalt', 'Andesite', 'Pumice']
7
Granite
Limestone
Pumice
Granite
Limestone
Pumice
['Name:Umar', 'Age:', 25, 'Height:', 1.69, 'Marital Statu:', 'Single', 'Adreess:', 'Bauchi']
['Facebook', 'Google', 'Microsoft', 'Apple', 'IBM', 'Amazon']
['Facebook', 'Google', 'Microsoft', 'Apple', 'IBM', 'Amazon']
6
Facebook
Apple
Amazon
Facebook Apple Amazon
['Facebook', 'Google', 'Microsoft', 'Apple', 'IBM', 'Amazon', 'Geo Data Solution']
['Facebook', 'Google', 'Microsoft', 'Tesla', 'Apple', 'IBM', 'Amazon', 'Geo Data Solution']
['Facebook', 'Google', 'Microsoft', 'TESLA', 'Apple', 'IBM', 'Amazon', 'Geo Data Solution']
Facebook #Google #Microsoft #TESLA #Apple #IBM #Amazon #Geo Data Solution
False
No, Tesla doesn't exists in the List!
['Amazon', 'Apple', 'Facebook', 'Geo Data Solution', 'Google', 'IBM', 'Microsoft', 'TESLA']
['TESLA', 'Microsoft', 'IBM', 'Google', 'Geo Data Solution', 'Facebook', 'Apple', 'Amazon']
['TESLA', 'Microsoft', 'IBM']
['Facebook', 'Apple', 'Amazon']
Geo Data Solution
['Microsoft', 'IBM', 'Google', 'Geo Data Solution', 'Facebook', 'Apple', 'Amazon']
['Microsoft', 'IBM', 'Google', 'Facebook', 'Apple', 'Amazon']
['Microsoft', 'IBM', 'Google', 'Facebook', 'Apple']
[]
None
['HTML', 'CSS', 'JS', 'React', 'Redux', 'Node', 'Express', 'MongoDB']
['HTML', 'CSS', 'JS', 'React', 'Redux', 'Node', 'Express', 'MongoDB']
['HTML', 'CSS', 'JS', 'React', 'Redux', 'Python', 'SQL', 'Node', 'Express', 'MongoDB']

##### Exercises: Level 2

In [363]:
1#The following is a list of 10 students ages:
ages = [19, 22, 19, 24, 20, 25, 26, 24, 25, 24]
#Sort the list and find the min and max age
ages_Copy = ages.copy()
sort_ages = ages_Copy.sort()
print(ages_Copy)
min_ages = (min(ages_Copy))
print(min_ages)
max_ages = (max(ages_Copy))
print(max_ages)

#2Add the min age and the max age again to the list
Addition_min_Max = min_ages + max_ages
print(Addition_min_Max)

#3Find the median age (one middle item or two middle items divided by two)

n = len(ages_Copy)
print(n)

median_age = ages_Copy[n//2]
print(median_age)

#4Find the average age (sum of all items divided by their number )

average = sum(ages_Copy)/n
print(average)

#5Find the range of the ages (max minus min)

Number_range = (max_ages - min_ages)

print(Number_range)

#6Compare the value of (min - average) and (max - average), use abs() method
min_diff = abs(min_ages - average)
max_diff = abs(max_ages - average)

print(min_diff)
print(max_diff)
round_max_diff = round(max_diff, 2)
round_min_diff = round(min_diff, 2)
print(round_max_diff)
print(round_min_diff)

#7Find the middle country(ies) in the countries list

Countries = ['China', 'Russia', 'USA', 'Finland', 'Sweden', 'Norway', 'Denmark']

middle_Countries = len(Countries) // 2
print(Countries[middle_Countries])

#8Divide the countries list into two equal lists if it is even if not one more country for the first half.
middle_Countries = len(Countries) // 2

first_half = Countries[:middle_Countries]
second_half = Countries[middle_Countries:]

print(first_half)
print(second_half)

#8['China', 'Russia', 'USA', 'Finland', 'Sweden', 'Norway', 'Denmark']. Unpack the first three countries and the rest as scandic countries.
a, b, c, *scandic_countries = Countries

print(a)
print(b)
print(c)
print(scandic_countries)

[19, 19, 20, 22, 24, 24, 24, 25, 25, 26]
19
26
45
10
24
22.8
7
3.8000000000000007
3.1999999999999993
3.2
3.8
Finland
['China', 'Russia', 'USA']
['Finland', 'Sweden', 'Norway', 'Denmark']
China
Russia
USA
['Finland', 'Sweden', 'Norway', 'Denmark']

### Tuple Exercises
#### Tuple Exercises: Level 1

In [364]:
#1Create an empty tuple
Empty_Tuple = ()
print(Empty_Tuple)
print(f'This is {Empty_Tuple} the Sign of Empty Tuple')

#2Create a tuple containing names of your sisters and your brothers (imaginary siblings are fine)
Brother = ('Ola', 'Hamid', 'Aliyu', 'Usman')
Sister = ('Fatima', 'Sofiat', 'Rodiat', 'Kamilat')
print(Brother)
print(Sister)
Siblings = Brother + Sister
print(Siblings)

#3How many siblings do you have?
List_of_Sibling = len(Siblings)
print(List_of_Sibling)

#4Modify the siblings tuple and add the name of your father and mother and assign it to family_members

Family = Siblings + ('Abdullahi', 'Hajara')
print(Family)

()
This is () the Sign of Empty Tuple
('Ola', 'Hamid', 'Aliyu', 'Usman')
('Fatima', 'Sofiat', 'Rodiat', 'Kamilat')
('Ola', 'Hamid', 'Aliyu', 'Usman', 'Fatima', 'Sofiat', 'Rodiat', 'Kamilat')
8
('Ola', 'Hamid', 'Aliyu', 'Usman', 'Fatima', 'Sofiat', 'Rodiat', 'Kamilat', 'Abdullahi', 'Hajara')

### Tuple Exercises
#### Tuple Exercises: Level 2

In [365]:
1#Unpack siblings and parents from family_members

*Sibling1, Father, Mother = Family
print(Father)
print(Mother)
print(Sibling1)

#2Create fruits, vegetables and animal products tuples. Join the three tuples and assign it to a variable called food_stuff_tp.

Fruits = ('Orange', 'Mango', 'Lime', 'Apple')
Vegetable = ('Spinach', 'Carrot', 'Tomatoes','Pepper')
Animal_Product = ('Milk', 'Butter', 'Cheese', 'Beef')
Food_Stuff = Fruits + Vegetable + Animal_Product
print(Food_Stuff)

#3Change the about food_stuff_tp tuple to a food_stuff_lt list
Food_Stuff_List = list(Food_Stuff)
print(Food_Stuff_List)

#4Slice out the middle item or items from the food_stuff_tp tuple or food_stuff_lt list.

Food_Stuff_List_Mid = len(Food_Stuff_List) // 2
print(Food_Stuff_List[Food_Stuff_List_Mid])

#5Slice out the first three items and the last three items from food_staff_lt list

Food_Stuff_List_First_Three = Food_Stuff_List[0:3]
print(Food_Stuff_List_First_Three)


Food_Stuff_List_Last_Three = Food_Stuff_List[-3:]
print(Food_Stuff_List_Last_Three)

#6Delete the food_staff_tp tuple completely
del Food_Stuff
#print(Food_Stuff)
print(f'This name Food Stuff is not defined.\nWhich means Food_Stuff has been deleted with variable del!')

#7Check if an item exists in tuple:
#Check if 'Estonia' is a nordic country
#Check if 'Iceland' is a nordic country
nordic_countries = ('Denmark', 'Finland','Iceland', 'Norway', 'Sweden')

Check_1 = 'Estonia' in nordic_countries
print(Check_1)

if  'Estonia' in nordic_countries:
    print(f'Yes, Estonia exist in nordic Countries!')
else:
    print(f"No, Estonia doesn't exist in nordic Countries!")


Check_2 = 'Iceland' in nordic_countries
print(Check_2)

if  'Iceland' in nordic_countries:
    print(f'Yes, Iceland exist in nordic Countries!')
else:
    print(f"No, Iceland doesn't exist in nordic Countries!")

Abdullahi
Hajara
['Ola', 'Hamid', 'Aliyu', 'Usman', 'Fatima', 'Sofiat', 'Rodiat', 'Kamilat']
('Orange', 'Mango', 'Lime', 'Apple', 'Spinach', 'Carrot', 'Tomatoes', 'Pepper', 'Milk', 'Butter', 'Cheese', 'Beef')
['Orange', 'Mango', 'Lime', 'Apple', 'Spinach', 'Carrot', 'Tomatoes', 'Pepper', 'Milk', 'Butter', 'Cheese', 'Beef']
Tomatoes
['Orange', 'Mango', 'Lime']
['Butter', 'Cheese', 'Beef']
This name Food Stuff is not defined.
Which means Food_Stuff has been deleted with variable del!
False
No, Estonia doesn't exist in nordic Countries!
True
Yes, Iceland exist in nordic Countries!

### Set Exercises
#### Set Exercises: Level 1

In [366]:
#Find the length of the set it_companies
# sets
it_companies = {'Facebook', 'Google', 'Microsoft', 'Apple', 'IBM', 'Oracle', 'Amazon'}
A = {19, 22, 24, 20, 25, 26}
B = {19, 22, 20, 25, 26, 24, 28, 27}
age_Set = [22, 19, 24, 25, 26, 24, 25, 24]

It_set = len(it_companies)
print(It_set)

#2Add 'Twitter' to it_companies
IT_Copy_Co = it_companies.copy()
print(it_companies)
It_Companies_Update = IT_Copy_Co.add('Twitter')
print(IT_Copy_Co)

#3Insert multiple IT companies at once to the set it_companies

Companies_New = {'Geo Data Solution', 'ConniSoft', 'SpaceFox'}
#Multiple_It = IT_Copy_Co.update(['Geo Data Solution', 'ConniSoft', 'SpaceFox'])
Multiple_It = IT_Copy_Co.update({'Geo Data Solution', 'ConniSoft', 'SpaceFox'}) #Both ({}) and ([]) will work
print(IT_Copy_Co)

#4Remove one of the companies from the set it_companies
Remove_1_IT = IT_Copy_Co.remove('Oracle')
print(IT_Copy_Co)

#5What is the difference between remove and discard

print(f"Remove: Removes a specified element and raises a KeyError if the element doesn't exist.\nDiscard: Removes a specified element, but does not raise an error if the element doesn't exist.")

7
{'Facebook', 'IBM', 'Microsoft', 'Apple', 'Google', 'Amazon', 'Oracle'}
{'Facebook', 'IBM', 'Microsoft', 'Apple', 'Google', 'Twitter', 'Amazon', 'Oracle'}
{'Facebook', 'Apple', 'Twitter', 'SpaceFox', 'Amazon', 'Geo Data Solution', 'ConniSoft', 'IBM', 'Microsoft', 'Google', 'Oracle'}
{'Facebook', 'Apple', 'Twitter', 'SpaceFox', 'Amazon', 'Geo Data Solution', 'ConniSoft', 'IBM', 'Microsoft', 'Google'}
Remove: Removes a specified element and raises a KeyError if the element doesn't exist.
Discard: Removes a specified element, but does not raise an error if the element doesn't exist.

### Set Exercises
#### Set Exercises: Level 2

In [367]:
#1Join A and B

A_Join_B = A.union(B)
print(A_Join_B)

#2Find A intersection B
A_Intersect_B = A.intersection(B)
print(A_Intersect_B)

#3Is A subset of B
A_Subset_B = A.issubset(B)
print(A_Subset_B)

if  A.issubset(B):
    print(f'Yes, {A} is the subset of {B}!')
else:
    print(f'No, {A} is not the subset of {B}!')


#4Are A and B disjoint sets

A_Subset_B_Dis = A.isdisjoint(B)
print(A_Subset_B_Dis)

if  A.isdisjoint(B):
    print(f'Yes, {A} is Disjoint to {B}!')
else:
    print(f'No, {A} is not Disjoint to{B}!')

#5Join A with B and B with A

Join_AB = A.union(B)
Join_BA = B.union(A)
print(Join_AB)

#5What is the symmetric difference between A and B

Symmetrical_A_B = A.symmetric_difference(B)
print(Symmetrical_A_B)

#6Delete the sets completely
Set_A_Copy = A.copy()
Set_B_Copy = B.copy()
print(Set_A_Copy,Set_B_Copy)
del Set_A_Copy,Set_B_Copy
#print(Set_A_Copy)  This 
#print(Set_A_Copy)
print(f'This Sets A and B is not defined.\nWhich means Sets A and B has been deleted with variable del!')

{19, 20, 22, 24, 25, 26, 27, 28}
{19, 20, 22, 24, 25, 26}
True
Yes, {19, 20, 22, 24, 25, 26} is the subset of {19, 20, 22, 24, 25, 26, 27, 28}!
False
No, {19, 20, 22, 24, 25, 26} is not Disjoint to{19, 20, 22, 24, 25, 26, 27, 28}!
{19, 20, 22, 24, 25, 26, 27, 28}
{27, 28}
{19, 20, 22, 24, 25, 26} {19, 20, 22, 24, 25, 26, 27, 28}
This Sets A and B is not defined.
Which means Sets A and B has been deleted with variable del!

### Set Exercises
#### Set Exercises: Level 3

In [368]:
#Convert the ages to a set and compare the length of the list and the set, which one is bigger?

print(age_Set)

age_Set_Copy = age_Set.copy()
age_Set_Copy_to_Set = (set(age_Set_Copy))

print(age_Set_Copy_to_Set)

lenght_age_Set_Copy = len(age_Set_Copy)
lenght_age_Set_Copy_to_Set = len(age_Set_Copy_to_Set)

print(lenght_age_Set_Copy)
print(lenght_age_Set_Copy_to_Set)
print(f'These indicate that the List Ages is more longer than Set because List allow dupplicate while Set allow only Unique Values!')

#Explain the difference between the following data types: string, list, tuple and set

print(f'String: is a sequence of characters. Immutable (cannot be changed after creation) e.g "Hello World!"')
print(f'List: Is an ordered collection of items. Mutable (can be changed after creation) e.g List = [1,2,3,4,2,]')
print(f'Tuple: Is an ordered collection of items. Immutable e.g Tuple = (1,2,3,4,5,)')
print(f'Set: Is an unordered collection of unique items. Mutable. e.g Set = {1,2,3,4,5,6,6}')


#4I am a teacher and I love to inspire and teach people. How many unique words have been used in the sentence? Use the split methods and set to get the unique words.

Sentence_Last = 'I am a teacher and I love to inspire and teach people.'
Word_last = Sentence_Last.split()
print(Word_last)
Change_Word_to_Set = (set(Word_last))
print(Change_Word_to_Set)
Check_the_Length = len(Change_Word_to_Set)

print(Check_the_Length) #But The Sentence contain 12 Word due to the conversion to Set and check using Set it popup the uniques words which are 10

[22, 19, 24, 25, 26, 24, 25, 24]
{19, 22, 24, 25, 26}
8
5
These indicate that the List Ages is more longer than Set because List allow dupplicate while Set allow only Unique Values!
String: is a sequence of characters. Immutable (cannot be changed after creation) e.g "Hello World!"
List: Is an ordered collection of items. Mutable (can be changed after creation) e.g List = [1,2,3,4,2,]
Tuple: Is an ordered collection of items. Immutable e.g Tuple = (1,2,3,4,5,)
Set: Is an unordered collection of unique items. Mutable. e.g Set = (1, 2, 3, 4, 5, 6, 6)
['I', 'am', 'a', 'teacher', 'and', 'I', 'love', 'to', 'inspire', 'and', 'teach', 'people.']
{'love', 'teacher', 'and', 'people.', 'inspire', 'teach', 'I', 'a', 'am', 'to'}
10